#!/usr/bin/env python3
from __future__ import annotations

import argparse
import hashlib
import hmac
import json
import os
import re
import subprocess
import sys
import tempfile
from datetime import datetime, timezone
from pathlib import Path
from urllib.request import Request, urlopen

HOST_RE = re.compile(r"^[a-z0-9](?:[a-z0-9-]{0,61}[a-z0-9])?\.wwc\.best$")
SHA256_RE = re.compile(r"^[0-9a-f]{64}$")
RESERVED_HOSTS = {
    "admin.wwc.best",
    "admin-staging.wwc.best",
    "api.wwc.best",
    "assets.wwc.best",
    "cabinet.wwc.best",
    "dev.wwc.best",
    "fedorov-staging.wwc.best",
    "media.wwc.best",
    "staging.wwc.best",
    "static.wwc.best",
    "www.wwc.best",
}


class SnapshotError(ValueError):
    pass


def canonical_host_version(hosts: list[str]) -> str:
    return hashlib.sha256("\n".join(hosts).encode("utf-8")).hexdigest()


def verify_signature(body: bytes, header: str, secret: str) -> None:
    prefix = "sha256="
    if not header.startswith(prefix):
        raise SnapshotError("missing or malformed snapshot signature")
    expected = hmac.new(secret.encode("utf-8"), body, hashlib.sha256).hexdigest()
    if not hmac.compare_digest(header[len(prefix) :], expected):
        raise SnapshotError("snapshot signature mismatch")


def validate_snapshot(
    payload: object,
    *,
    expected_tenant: str,
    now: datetime | None = None,
    max_age_seconds: int = 300,
    max_future_seconds: int = 30,
) -> dict:
    if not isinstance(payload, dict):
        raise SnapshotError("snapshot must be an object")
    required = {"tenant_id", "generated_at", "version", "allowed_hosts"}
    if set(payload) != required:
        raise SnapshotError("snapshot schema mismatch")
    if payload["tenant_id"] != expected_tenant:
        raise SnapshotError("snapshot tenant mismatch")

    try:
        generated_at = datetime.fromisoformat(str(payload["generated_at"]).replace("Z", "+00:00"))
    except ValueError as exc:
        raise SnapshotError("invalid generated_at") from exc
    if generated_at.tzinfo is None or generated_at.utcoffset() is None:
        raise SnapshotError("generated_at must include timezone")
    current = (now or datetime.now(timezone.utc)).astimezone(timezone.utc)
    age = (current - generated_at.astimezone(timezone.utc)).total_seconds()
    if age > max_age_seconds:
        raise SnapshotError("snapshot is stale")
    if age < -max_future_seconds:
        raise SnapshotError("snapshot generated_at is in the future")

    hosts = payload["allowed_hosts"]
    if not isinstance(hosts, list) or not hosts:
        raise SnapshotError("allowed_hosts must be a non-empty list")
    if hosts != sorted(set(hosts)):
        raise SnapshotError("allowed_hosts must be sorted and unique")
    for host in hosts:
        if not isinstance(host, str) or not HOST_RE.fullmatch(host):
            raise SnapshotError("invalid partner hostname")
        if host in RESERVED_HOSTS:
            raise SnapshotError("reserved hostname in partner snapshot")

    version = payload["version"]
    if not isinstance(version, str) or not SHA256_RE.fullmatch(version):
        raise SnapshotError("invalid snapshot version")
    if not hmac.compare_digest(version, canonical_host_version(hosts)):
        raise SnapshotError("snapshot version does not match allowed_hosts")
    return payload


def render_nginx_map(snapshot: dict) -> str:
    lines = [
        "# Generated by sync_partner_host_map.py. Do not edit.",
        f"# tenant={snapshot['tenant_id']} version={snapshot['version']}",
        "map $host $wwc_partner_access_allowed {",
        "    hostnames;",
        "    default 0;",
    ]
    lines.extend(f"    {host} 1;" for host in snapshot["allowed_hosts"])
    lines.extend(["}", ""])
    return "\n".join(lines)


def fetch_snapshot(endpoint: str, tenant_host: str, secret: str, timeout: float) -> tuple[bytes, str]:
    request = Request(
        endpoint,
        headers={
            "Accept": "application/json",
            "X-WWC-Edge-Secret": secret,
            "X-Forwarded-Host": tenant_host,
        },
        method="GET",
    )
    with urlopen(request, timeout=timeout) as response:
        if response.status != 200:
            raise SnapshotError(f"snapshot endpoint returned HTTP {response.status}")
        return response.read(), response.headers.get("X-WWC-Snapshot-Signature", "")


def run_checked(command: list[str]) -> None:
    result = subprocess.run(command, check=False, capture_output=True, text=True)
    if result.returncode:
        detail = (result.stderr or result.stdout).strip().splitlines()
        raise SnapshotError(detail[-1] if detail else f"command failed: {command[0]}")


def validate_candidate(candidate: Path, nginx: str) -> None:
    with tempfile.TemporaryDirectory(prefix="wwc-nginx-check-") as directory:
        root = Path(directory)
        config = root / "nginx.conf"
        config.write_text(
            "events {}\nhttp {\n"
            f"    include {candidate.as_posix()};\n"
            "    server { listen 127.0.0.1:18080; server_name _; }\n"
            "}\n",
            encoding="utf-8",
        )
        run_checked([nginx, "-t", "-q", "-p", f"{root}{os.sep}", "-c", str(config)])


def atomic_write(path: Path, content: bytes) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    fd, temporary = tempfile.mkstemp(prefix=f".{path.name}.", dir=path.parent)
    try:
        with os.fdopen(fd, "wb") as handle:
            handle.write(content)
            handle.flush()
            os.fsync(handle.fileno())
        os.replace(temporary, path)
    finally:
        if os.path.exists(temporary):
            os.unlink(temporary)


def install_map(*, output: Path, state_path: Path, rendered: bytes, snapshot: dict, nginx: str) -> bool:
    previous = output.read_bytes() if output.exists() else None
    if previous == rendered:
        atomic_write(state_path, json.dumps(snapshot, sort_keys=True).encode("utf-8") + b"\n")
        return False

    fd, candidate_name = tempfile.mkstemp(prefix=".wwc-partner-map.", suffix=".conf", dir=output.parent)
    os.close(fd)
    candidate = Path(candidate_name)
    try:
        candidate.write_bytes(rendered)
        validate_candidate(candidate, nginx)
        os.replace(candidate, output)
        try:
            run_checked([nginx, "-t", "-q"])
            run_checked(["systemctl", "reload", "nginx"])
        except Exception:
            if previous is not None:
                atomic_write(output, previous)
                run_checked([nginx, "-t", "-q"])
                run_checked(["systemctl", "reload", "nginx"])
            else:
                output.unlink(missing_ok=True)
            raise
        atomic_write(state_path, json.dumps(snapshot, sort_keys=True).encode("utf-8") + b"\n")
        return True
    finally:
        candidate.unlink(missing_ok=True)


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Safely synchronize paid WWC partner hosts")
    parser.add_argument("--endpoint", required=True)
    parser.add_argument("--tenant", required=True)
    parser.add_argument("--tenant-host", required=True)
    parser.add_argument("--output", type=Path, required=True)
    parser.add_argument("--state", type=Path, required=True)
    parser.add_argument("--secret-env", default="PLATFORM_EDGE_SNAPSHOT_SECRET")
    parser.add_argument("--timeout", type=float, default=10.0)
    parser.add_argument("--max-age-seconds", type=int, default=300)
    parser.add_argument("--nginx", default="nginx")
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    secret = os.environ.get(args.secret_env, "")
    if not secret:
        print(f"edge sync failed: missing secret env {args.secret_env}", file=sys.stderr)
        return 2
    try:
        body, signature = fetch_snapshot(args.endpoint, args.tenant_host, secret, args.timeout)
        verify_signature(body, signature, secret)
        payload = validate_snapshot(
            json.loads(body),
            expected_tenant=args.tenant,
            max_age_seconds=args.max_age_seconds,
        )
        args.output.parent.mkdir(parents=True, exist_ok=True)
        changed = install_map(
            output=args.output,
            state_path=args.state,
            rendered=render_nginx_map(payload).encode("utf-8"),
            snapshot=payload,
            nginx=args.nginx,
        )
    except Exception as exc:
        print(f"edge sync failed; last-known-good preserved: {exc}", file=sys.stderr)
        return 1
    print(f"edge sync ok: version={payload['version']} changed={str(changed).lower()}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
