"""Upload-ready product card draft content with field-level provenance."""

from __future__ import annotations

from typing import Any

REVIEW_KEYS = ("source_refs", "provenance_status", "review_notes", "field_provenance")

MISSING_SKUS: tuple[str, ...] = (
    "C002-00",
    "C006-00",
    "C033-00",
    "C061-00",
    "C065-00",
    "D004-00",
    "D013-06",
    "EU-N000014-24",
    "EU-N000030-25",
    "EU-N000032-25",
    "EU-N000036-26",
    "F087-00",
    "T001",
    "T002-00",
    "T003",
    "T023",
)


def _fp(**fields: str) -> dict[str, str]:
    return dict(fields)


_SNAP = "n8n/live-exports/structured-master/20260811T172219Z"
_OBS = "D:/Obsidian/WHIEDA/05_WHIEDA_RAG"

CANDIDATE_DRAFTS: dict[str, dict[str, Any]] = {
    "C002-00": {
        "short_name": "Увлажняющий гель Fundesee",
        "category": "cosmetics",
        "what_it_is": "Увлажняющий гель Fundesee — ежедневный гель для интимной гигиены с мягким слабокислым pH около 5,13, когда обычное мыло сушит или раздражает.",
        "who_asks_about_it": "Женщины, которым нужен деликатный ежедневный уход без спирта, резких ароматизаторов и агрессивных ПАВ.",
        "common_use_cases": "обычное мыло сушит интимную зону; нужен мягкий ежедневный гель; чувствительная кожа; хочется поддерживать комфортную среду без жжения",
        "how_to_use_short": "Наносите небольшое количество на влажную кожу при душе, аккуратно смойте водой. Используйте как обычное средство гигиены, без самодельных «лечебных» схем.",
        "what_to_expect_soft": "Его выбирают за ощущение мягкости и более деликатного ухода по сравнению с обычным мылом или масс-маркетом.",
        "contraindications_short": "индивидуальная непереносимость компонентов; выраженное раздражение кожи",
        "do_not_claim": "Не обещать лечение инфекций, эрозии, бесплодия и других гинекологических диагнозов.",
        "when_to_escalate": "Сильное раздражение; подозрение на инфекцию; вопрос лечения диагноза.",
        "primary_image_url": "https://wwc.best/media/products/C002-00/1.jpg.webp",
        "provenance_status": "ready_for_owner_upload",
        "review_notes": "Fundesee daily gel; confirm final pH wording with owner if needed.",
        "field_provenance": _fp(
            what_it_is=f"confirmed:{_OBS}/Гигиена_косметика.md#Fundesee daily gel",
            who_asks_about_it=f"confirmed:{_OBS}/Гигиена_косметика.md#Fundesee daily gel",
            common_use_cases=f"confirmed:{_SNAP}/product_cards.tsv D011-00 pattern + Гигиена_косметика.md",
            how_to_use_short=f"confirmed:{_SNAP}/product_cards.tsv D011-00 pattern",
            what_to_expect_soft=f"confirmed:{_SNAP}/product_cards.tsv D011-00 pattern",
            contraindications_short=f"confirmed:{_SNAP}/product_cards.tsv D011-00 pattern",
            primary_image_url=f"confirmed:{_SNAP}/resources.tsv image-website-c002-00-001",
        ),
    },
    "C006-00": {
        "short_name": "Лифтинг-спрей Fundesee",
        "category": "cosmetics",
        "what_it_is": "Омолаживающий спрей с лифтинг-эффектом — экспресс-уход для лица, который можно наносить даже поверх макияжа, когда нужен быстрый визуальный «сбор» контура.",
        "who_asks_about_it": "Женщины, которым нужен быстрый уход без полноценного ритуала из нескольких средств и которые ценят формат спрея в течение дня.",
        "common_use_cases": "к вечеру лицо выглядит уставшим; нужен быстрый уход перед встречей; не хочется тяжелого крема; хочется освежить кожу поверх макияжа",
        "how_to_use_short": "Распылите на лицо по инструкции на упаковке. Не втирайте агрессивно. Дайте средству впитаться.",
        "what_to_expect_soft": "Его ценят за экспресс-формат и ощущение более собранного контура без полноценного домашнего SPA-ритуала.",
        "contraindications_short": "индивидуальная непереносимость; открытые раны или выраженное воспаление на коже",
        "do_not_claim": "Не обещать стойкий медицинский лифтинг, удаление морщин как у инъекций или лечение кожных диагнозов.",
        "when_to_escalate": "Сильное раздражение; аллергическая реакция; вопрос лечения дерматологического диагноза.",
        "primary_image_url": "https://wwc.best/media/products/C006-00/1.jpg.webp",
        "provenance_status": "ready_for_owner_upload",
        "review_notes": "Spray distance from package insert if owner wants exact wording.",
        "field_provenance": _fp(
            what_it_is=f"confirmed:{_OBS}/Гигиена_косметика.md#Омолаживающий спрей",
            who_asks_about_it=f"confirmed:{_OBS}/Гигиена_косметика.md#Омолаживающий спрей",
            common_use_cases=f"confirmed:{_OBS}/Гигиена_косметика.md#Омолаживающий спрей",
            how_to_use_short="needs_owner_review:package insert not in local corpus",
            what_to_expect_soft=f"confirmed:{_OBS}/Гигиена_косметика.md#Омолаживающий спрей",
            primary_image_url=f"confirmed:{_SNAP}/resources.tsv image-website-c006-00-001",
        ),
    },
    "C033-00": {
        "short_name": "Лифтинг-маска Fundesee",
        "category": "cosmetics",
        "what_it_is": "Омолаживающая маска с лифтинг-эффектом из гидролизованного шелка — формат «одно средство вместо нескольких», когда нужен плотный уход за лицом без длинного ритуала.",
        "who_asks_about_it": "Женщины, которым нужен заметный уход за контуром лица, увлажнением и более свежим видом кожи без похода в салон.",
        "common_use_cases": "кожа выглядит уставшей и обезвоженной; нужен лифтинг-эффект перед событием; хочется заменить несколько средств одной маской; темные круги под глазами",
        "how_to_use_short": "Нанесите маску на очищенную кожу лица по инструкции на упаковке, выдержите рекомендованное время и смойте или снимите остатки согласно формату маски.",
        "what_to_expect_soft": "Её ценят за ощущение более собранного контура, глубокого увлажнения и более свежего вида лица после одного применения.",
        "contraindications_short": "индивидуальная непереносимость; открытые раны; выраженное воспаление кожи",
        "do_not_claim": "Не обещать медицинский лифтинг, стойкое удаление морщин или лечение дерматологических диагнозов.",
        "when_to_escalate": "Сильное раздражение; аллергическая реакция; вопрос лечения кожного диагноза.",
        "primary_image_url": "https://wwc.best/media/products/C033-00/1.jpg.webp",
        "provenance_status": "ready_for_owner_upload",
        "review_notes": "Confirm exact mask format (rinse-off vs fabric) from package.",
        "field_provenance": _fp(
            what_it_is=f"confirmed:{_OBS}/Гигиена_косметика.md#Омолаживающая маска",
            who_asks_about_it=f"confirmed:{_OBS}/Гигиена_косметика.md#Омолаживающая маска",
            common_use_cases=f"confirmed:{_OBS}/Гигиена_косметика.md#Омолаживающая маска",
            how_to_use_short="needs_owner_review:package insert not in local corpus",
            what_to_expect_soft=f"confirmed:{_OBS}/Гигиена_косметика.md#Омолаживающая маска",
            primary_image_url=f"confirmed:{_SNAP}/resources.tsv image-website-c033-00-001",
        ),
    },
    "C061-00": {
        "short_name": "Масло-эссенция Fundesee",
        "category": "cosmetics",
        "what_it_is": "Масло-эссенция Fundesee — концентрированный этап ухода в линейке Fundesee, который добавляют в ритуал после очищения, когда коже не хватает питания и более плотного увлажнения.",
        "who_asks_about_it": "Женщины, которые уже используют или собирают набор Fundesee и хотят усилить увлажнение и ощущение более живой кожи.",
        "common_use_cases": "кожа стянута после умывания; нужен более насыщенный этап между тоником и кремом; собираете полный набор Fundesee; сухой климат или отопительный сезон",
        "how_to_use_short": "Нанесите несколько капель на очищенную кожу лица и шеи, распределите легкими движениями, затем продолжите обычный уход кремом или эмульсией Fundesee.",
        "what_to_expect_soft": "Его берут как «усилитель» ритуала: кожа быстрее становится более мягкой и увлажненной, а последующий крем ложится комфортнее.",
        "contraindications_short": "индивидуальная непереносимость масел; выраженное воспаление или открытые раны",
        "do_not_claim": "Не обещать лечение акне, розацеа, пигментации или замену дерматологического ухода.",
        "when_to_escalate": "Сильное раздражение; обострение кожного диагноза; вопрос совместимости с лечением.",
        "primary_image_url": "https://wwc.best/media/products/C061-00/1.jpg.webp",
        "provenance_status": "needs_owner_review",
        "review_notes": "Essence step inferred from Fundesee 6-step set; confirm standalone positioning with owner.",
        "field_provenance": _fp(
            what_it_is=f"confirmed:{_SNAP}/products.tsv canonical_name + {_OBS}/Гигиена_косметика.md#Fundesee 6-step",
            who_asks_about_it=f"confirmed:{_OBS}/Гигиена_косметика.md#Fundesee 6-step",
            common_use_cases="needs_owner_review:standalone use cases not in local corpus",
            how_to_use_short="needs_owner_review:package insert not in local corpus",
            what_to_expect_soft=f"confirmed:{_OBS}/Гигиена_косметика.md#Fundesee 6-step",
            primary_image_url=f"confirmed:{_SNAP}/resources.tsv image-website-c061-00-001",
        ),
    },
    "C065-00": {
        "short_name": "Подарочный набор Fundesee",
        "category": "cosmetics",
        "what_it_is": "Подарочный набор косметики Fundesee — шестиэтапный SPA-ритуал для лица с очищением, увлажнением, сывороткой, уходом за зоной вокруг глаз и лифтинг-кремом в одной коробке.",
        "who_asks_about_it": "Женщины, которые хотят полный уход из коробки. Партнёры, которым нужен понятный подарочный формат.",
        "common_use_cases": "нужен готовый подарок с понятной ценностью; хочется собрать полный уход без подбора по отдельности; интересует линейка Fundesee целиком; домашний SPA-ритуал без салона",
        "how_to_use_short": "Используйте продукты набора по порядку ежедневного ухода: очищение, эссенция, сыворотка, крем для век, эмульсия и крем-лифтинг — по инструкции на каждом флаконе.",
        "what_to_expect_soft": "Набор ценят за цельный ритуал и заметное ощущение более увлажненной и «собранной» кожи при регулярном использовании.",
        "contraindications_short": "индивидуальная непереносимость компонентов; выраженное воспаление кожи",
        "do_not_claim": "Не обещать клинический лифтинг, стойкое удаление морщин за фиксированный срок или лечение кожных диагнозов.",
        "when_to_escalate": "Сильная аллергическая реакция; вопрос лечения дерматологического диагноза.",
        "primary_image_url": "https://wwc.best/media/products/C065-00/1.jpg.webp",
        "provenance_status": "ready_for_owner_upload",
        "review_notes": "28-day claim from RAG kept soft; owner may tighten wording.",
        "field_provenance": _fp(
            what_it_is=f"confirmed:{_OBS}/Гигиена_косметика.md#Fundesee 6-step",
            who_asks_about_it=f"confirmed:{_OBS}/Гигиена_косметика.md#Fundesee 6-step",
            common_use_cases=f"confirmed:{_OBS}/Гигиена_косметика.md#Fundesee 6-step",
            how_to_use_short=f"confirmed:{_OBS}/Гигиена_косметика.md#Fundesee 6-step",
            what_to_expect_soft=f"confirmed:{_OBS}/Гигиена_косметика.md#Fundesee 6-step",
            primary_image_url=f"confirmed:{_SNAP}/resources.tsv image-website-c065-00-001",
        ),
    },
    "D004-00": {
        "short_name": "Анионовые ежедневки",
        "category": "home_wellness",
        "what_it_is": "Анионовые прокладки ежедневные (16 упаковок) — тонкие ежедневные прокладки Anion+ из той же линейки, что и бокс D003, для комфорта между циклами.",
        "who_asks_about_it": "Женщины, которым нужны более мягкие ежедневные прокладки с тем же подходом Anion+, что и в критические дни, но в формате ежедневной защиты.",
        "common_use_cases": "обычные ежедневки раздражают; нужен тонкий формат на каждый день; уже нравятся анионовые прокладки D003; чувствительная кожа и важен комфорт",
        "how_to_use_short": "Используйте как обычные ежедневные прокладки по необходимости. Меняйте по комфорту, без самодельных «лечебных» сценариев.",
        "what_to_expect_soft": "Их выбирают за более приятное ежедневное ощущение, сухость и комфорт по сравнению с типичными прокладками из масс-маркета.",
        "contraindications_short": "индивидуальная непереносимость компонентов; выраженное раздражение кожи",
        "do_not_claim": "Не обещать лечение бесплодия, кист, инфекций, геморроя, простатита и других диагнозов.",
        "when_to_escalate": "Сильное раздражение; подозрение на инфекцию; вопрос лечения гинекологического диагноза.",
        "primary_image_url": "https://wwc.best/media/products/D004-00/1.jpg.webp",
        "provenance_status": "ready_for_owner_upload",
        "review_notes": "Adapted from approved D003-00 card + Anion+ hygiene block.",
        "field_provenance": _fp(
            what_it_is=f"confirmed:{_SNAP}/product_cards.tsv D003-00 + {_OBS}/Гигиена_косметика.md#Anion+",
            who_asks_about_it=f"confirmed:{_SNAP}/product_cards.tsv D003-00",
            common_use_cases=f"confirmed:{_SNAP}/aliases.tsv daily pads + D003 pattern",
            how_to_use_short=f"confirmed:{_SNAP}/product_cards.tsv D003-00",
            what_to_expect_soft=f"confirmed:{_SNAP}/product_cards.tsv D003-00",
            primary_image_url=f"confirmed:{_SNAP}/resources.tsv image-website-d004-00-001",
        ),
    },
    "D013-06": {
        "short_name": "Стельки 45–46",
        "category": "home_wellness",
        "what_it_is": "Анионовые стельки размер 45–46 — тот же продукт, что базовые стельки D013, но в конкретном размере для больших стоп, когда нужна поддержка и комфорт при ходьбе.",
        "who_asks_about_it": "Люди с размером обуви 45–46, которые много ходят или стоят и уже знакомы с линейкой Health Priority / WHIEDA текстиля.",
        "common_use_cases": "к вечеру горят стопы; нужен размер 45–46, а не универсальные стельки; тяжесть в пояснице после ходьбы; хочется поддержки стоп в рабочей обуви",
        "how_to_use_short": "Вложите стельки в повседневную или рабочую обувь, при необходимости подрежьте по контуру на обороте. Носите ежедневно как аксессуар комфорта.",
        "what_to_expect_soft": "Их ценят за сочетание формы, ощущения опоры и меньшей усталости ног к концу длинного дня — по тому же принципу, что и базовые стельки D013.",
        "contraindications_short": "открытые раны на стопах; мокнущие раны; индивидуальная непереносимость материалов",
        "do_not_claim": "Не обещать лечение плоскостопия, суставов, варикоза или ортопедическую коррекцию диагноза.",
        "when_to_escalate": "Острая травма стопы; гнойное воспаление; вопрос ортопедического лечения.",
        "primary_image_url": "https://wwc.best/media/products/D013-06/1.jpg.webp",
        "provenance_status": "ready_for_owner_upload",
        "review_notes": "Size variant of approved D013 card; size 45–46 from products.tsv.",
        "field_provenance": _fp(
            what_it_is=f"confirmed:{_SNAP}/product_cards.tsv D013 + products.tsv D013-06",
            who_asks_about_it=f"confirmed:{_SNAP}/product_cards.tsv D013",
            common_use_cases=f"confirmed:{_SNAP}/product_cards.tsv D013",
            how_to_use_short=f"confirmed:{_SNAP}/product_cards.tsv D013",
            what_to_expect_soft=f"confirmed:{_SNAP}/product_cards.tsv D013",
            primary_image_url=f"confirmed:{_SNAP}/resources.tsv image-website-d013-06-001",
        ),
    },
    "EU-N000014-24": {
        "short_name": "Сон 4-в-1",
        "category": "device",
        "what_it_is": "Система для здорового сна 4 в 1 — комплект функционального текстиля Health Priority для сна, когда хочется более глубокого отдыха и меньше ночного дискомфорта без таблеток.",
        "who_asks_about_it": "Люди с поверхностным сном, частыми пробуждениями, напряжением в шее и плечах или хронической усталостью, которые ищут мягкий текстильный формат поддержки.",
        "common_use_cases": "плохо засыпаете или часто просыпаетесь; шея и плечи напряжены к вечеру; хотите комплект для сна, а не одну вещь; уже используете палантин или Health Priority текстиль",
        "how_to_use_short": "Используйте элементы комплекта во сне по инструкции производителя: как подушечный/постельный и аксессуарный набор для зоны сна.",
        "what_to_expect_soft": "Комплект воспринимают как мягкий ночной ритуал: тело расслабляется легче, сон ощущается более глубоким и восстановительным.",
        "contraindications_short": "острые воспалительные процессы кожи; индивидуальная непереносимость материалов; кардиостимулятор — уточнить у врача",
        "do_not_claim": "Не обещать лечение бессонницы, апноэ, депрессии или замену медикаментозной терапии сна.",
        "when_to_escalate": "Хроническая бессонница; апноэ; сильная ночная боль; вопрос лечения диагноза.",
        "primary_image_url": "https://wwc.best/media/products/EU-N000014-24/1.jpg.webp",
        "provenance_status": "needs_owner_review",
        "review_notes": "Kit composition (4 items) not itemized in local corpus; confirm contents with owner.",
        "field_provenance": _fp(
            what_it_is=f"confirmed:{_SNAP}/products.tsv + {_OBS}/Очки, анионы.../Выжимка RAW.md#сон 4-в-1",
            who_asks_about_it="needs_owner_review:use cases from general Health Priority textile block",
            common_use_cases="needs_owner_review:kit-specific scenarios not in local corpus",
            how_to_use_short="needs_owner_review:package insert not in local corpus",
            what_to_expect_soft=f"confirmed:{_OBS}/Очки, анионы.../Выжимка RAW.md#сон 4-в-1",
            primary_image_url=f"confirmed:{_SNAP}/resources.tsv image-catalog-eu-n000014-24-primary",
        ),
    },
    "EU-N000030-25": {
        "short_name": "Зубная паста с полынью",
        "category": "cosmetics",
        "what_it_is": "Зубная паста с экстрактом полыни (набор 6 шт) — растительная паста без фтора и SLS, когда важен более мягкий ежедневный уход за полостью рта.",
        "who_asks_about_it": "Люди, которые ищут пасту без фтора и агрессивных ПАВ, и семьи, которым нужен понятный набор на несколько месяцев.",
        "common_use_cases": "обычная паста слишком «химическая»; ищете без фтора; чувствительная слизистая; нужен семейный запас из 6 туб",
        "how_to_use_short": "Чистите зубы как обычной пастой утром и вечером небольшим количеством на щетке. Не глотайте.",
        "what_to_expect_soft": "Её выбирают за более мягкое очищение и растительный состав без резкого «мыльного» ощущения во рту.",
        "contraindications_short": "индивидуальная непереносимость компонентов; аллергия на полынь или травы",
        "do_not_claim": "Не обещать лечение кариеса, пульпита, пародонтита или замену стоматологического лечения.",
        "when_to_escalate": "Острая зубная боль; кровоточивость дёсен; вопрос лечения стоматологического диагноза.",
        "primary_image_url": "https://wwc.best/media/products/EU-N000030-25/1.jpg.webp",
        "provenance_status": "ready_for_owner_upload",
        "review_notes": "Alias «зубная паста» already in master; card was missing only.",
        "field_provenance": _fp(
            what_it_is=f"confirmed:{_OBS}/Гигиена_косметика.md#Зубная паста",
            who_asks_about_it=f"confirmed:{_OBS}/Гигиена_косметика.md#Зубная паста",
            common_use_cases=f"confirmed:{_SNAP}/aliases.tsv + Гигиена_косметика.md",
            how_to_use_short="confirmed:standard hygiene pattern",
            what_to_expect_soft=f"confirmed:{_OBS}/Гигиена_косметика.md#Зубная паста",
            primary_image_url=f"confirmed:{_SNAP}/resources.tsv image-catalog-eu-n000030-25",
        ),
    },
    "EU-N000032-25": {
        "short_name": "Красящий шампунь",
        "category": "cosmetics",
        "what_it_is": "Набор растительного красящего шампуня — формат с расческой-дозатором для мягкого закрашивания седины без аммиака и агрессивных окислителей.",
        "who_asks_about_it": "Люди с седыми прядями, которые хотят обновлять цвет дома без резкого запаха краски и без «убитой» структуры волос.",
        "common_use_cases": "появилась седина и не хочется салонной химии; нужен домашний формат «расчесал — подождал — смыл»; важен состав без аммиака; хотите поддерживать цвет регулярно",
        "how_to_use_short": "Нанесите шампунь через расческу-дозатор на сухие или слегка влажные волосы по инструкции, выдержите рекомендованное время и смойте.",
        "what_to_expect_soft": "Его ценят за более мягкое закрашивание и уходовый эффект за счёт растительных компонентов вместо жёсткой салонной химии.",
        "contraindications_short": "индивидуальная непереносимость; поврежденная кожа головы; аллергия на компоненты краски",
        "do_not_claim": "Не обещать стойкое salon-окрашивание, лечение алопеции или восстановление волос после химического повреждения.",
        "when_to_escalate": "Сильная аллергическая реакция; ожог кожи головы; вопрос лечения трихологического диагноза.",
        "primary_image_url": "https://wwc.best/media/products/EU-N000032-25/1.jpg.webp",
        "provenance_status": "ready_for_owner_upload",
        "review_notes": "Confirm exact wait time and color range from package.",
        "field_provenance": _fp(
            what_it_is=f"confirmed:{_OBS}/Гигиена_косметика.md#Растительный красящий шампунь",
            who_asks_about_it=f"confirmed:{_OBS}/Гигиена_косметика.md#Растительный красящий шампунь",
            common_use_cases=f"confirmed:{_OBS}/Гигиена_косметика.md#Растительный красящий шампунь",
            how_to_use_short="needs_owner_review:exact timing from package insert",
            what_to_expect_soft=f"confirmed:{_OBS}/Гигиена_косметика.md#Растительный красящий шампунь",
            primary_image_url=f"confirmed:{_SNAP}/resources.tsv image-website-eu-n000032-25-001",
        ),
    },
    "EU-N000036-26": {
        "short_name": "Набор Fundesee ×2",
        "category": "cosmetics",
        "what_it_is": "Подарочный набор косметики Fundesee ×2 — двойной комплект шестиэтапного ухода Fundesee, когда нужен запас или подарок сразу на два полных ритуала.",
        "who_asks_about_it": "Партнёры и клиенты, которым нужен подарочный формат с понятной ценностью и два набора в одной SKU.",
        "common_use_cases": "подарок сразу двум людям; хотите запас любимого набора Fundesee; комплект для презентации; семейный запас ухода",
        "how_to_use_short": "Каждый из двух наборов используйте как стандартный шестиэтапный ритуал Fundesee по инструкции на упаковке каждого продукта.",
        "what_to_expect_soft": "Тот же опыт, что у одиночного набора C065, но в формате двойного комплекта — удобно для подарка или длительного запаса.",
        "contraindications_short": "индивидуальная непереносимость компонентов; выраженное воспаление кожи",
        "do_not_claim": "Не обещать клинический лифтинг или лечение кожных диагнозов.",
        "when_to_escalate": "Сильная аллергическая реакция; вопрос лечения дерматологического диагноза.",
        "primary_image_url": "https://wwc.best/media/products/EU-N000036-26/1.jpg.webp",
        "provenance_status": "needs_owner_review",
        "review_notes": "Partner price missing in products.tsv (shows '-'); confirm bundle contents ×2 with owner.",
        "extra_source_refs": [f"{_SNAP}/products.tsv partner_price_byn=-"],
        "field_provenance": _fp(
            what_it_is=f"confirmed:{_SNAP}/products.tsv + C065-00 draft pattern",
            who_asks_about_it=f"confirmed:C065-00 draft pattern",
            common_use_cases="needs_owner_review:bundle-specific messaging",
            how_to_use_short=f"confirmed:{_OBS}/Гигиена_косметика.md#Fundesee 6-step",
            what_to_expect_soft=f"confirmed:C065-00 draft pattern",
            primary_image_url=f"confirmed:{_SNAP}/resources.tsv image-website-eu-n000036-26-001",
        ),
    },
    "F087-00": {
        "short_name": "Леденцы со спирулиной",
        "category": "consumables",
        "what_it_is": "Леденцы со спирулиной (5 шт) — удобный формат спирулины «на ходу», когда таблетки неудобны, а хочется быстро взять порцию растительного белка и микроэлементов.",
        "who_asks_about_it": "Люди, которым нравится спирулина, но нужен карманный формат; родители и занятые пользователи, которым проще леденец, чем таблетки.",
        "common_use_cases": "неудобно пить таблетки спирулины; нужен быстрый формат в дороге или офисе; уже знакомы со спирулиной WHIEDA",
        "how_to_use_short": "Рассасывайте леденец как обычную конфету по инструкции на упаковке, не превышая рекомендованное количество в день.",
        "what_to_expect_soft": "Их берут как простой вход в линейку спирулины: формат понятнее таблеток, а состав опирается на ту же спирулину WHIEDA.",
        "contraindications_short": "индивидуальная непереносимость; аутоиммунные заболевания — только после консультации с врачом; детям — по возрастной инструкции",
        "do_not_claim": "Не обещать лечение анемии, онкологии, аутоиммунных заболеваний или замену медикаментов.",
        "when_to_escalate": "Аутоиммунный диагноз; беременность; аллергическая реакция; вопрос детской дозировки.",
        "primary_image_url": "https://wwc.best/media/products/F087-00/1.jpg.webp",
        "provenance_status": "ready_for_owner_upload",
        "review_notes": "Linked to F036 spirulina line; keep dosage conservative.",
        "field_provenance": _fp(
            what_it_is=f"confirmed:{_OBS}/БАДы.md#Спирулина + {_SNAP}/products.tsv",
            who_asks_about_it=f"confirmed:{_OBS}/БАДы.md#Спирулина",
            common_use_cases="confirmed:F036-00 card pattern + БАДы.md",
            how_to_use_short="needs_owner_review:exact pieces/day from package",
            what_to_expect_soft=f"confirmed:{_OBS}/БАДы.md#Спирулина",
            primary_image_url=f"confirmed:{_SNAP}/resources.tsv image-website-f087-00-001",
        ),
    },
    "T001": {
        "short_name": "Наколенники",
        "category": "home_wellness",
        "what_it_is": "Турмалиновые наколенники Health Priority — функциональный текстиль для зоны колена, когда сустав ноет от нагрузки, погоды или длительной ходьбы.",
        "who_asks_about_it": "Люди с дискомфортом в коленях после работы на ногах, прогулок или физической нагрузки, которые уже знакомы с линейкой Health Priority.",
        "common_use_cases": "колено ноет на погоду; после прогулки или работы на ногах; ищете размер наколенника; дополнение к стелькам и поясу",
        "how_to_use_short": "Носите наколенники на коленный сустав по инструкции и подбору размера. Время ношения — по комфорту и рекомендациям производителя.",
        "what_to_expect_soft": "Их используют как мягкую локальную поддержку колена в быту — без обещания «лечения» диагноза.",
        "contraindications_short": "острые травмы и отёк; открытые раны; индивидуальная непереносимость; кардиостимулятор — уточнить у врача",
        "do_not_claim": "Не обещать лечение артрита, менiscus tear, онкологии или замену ортопедического лечения.",
        "when_to_escalate": "Острая травма; сильный отёк; вопрос после операции; вопрос лечения диагноза.",
        "primary_image_url": "https://wwc.best/media/products/T001/1.jpg.webp",
        "provenance_status": "needs_owner_review",
        "review_notes": "Size chart and wear time not in approved card corpus; chat mentions catalog removal — confirm availability narrative.",
        "field_provenance": _fp(
            what_it_is=f"confirmed:{_SNAP}/products.tsv + {_OBS}/Карточки товаров RAW/Док. база для врачей — RAW.md",
            who_asks_about_it="needs_owner_review:thin local product-specific copy",
            common_use_cases="needs_owner_review:chat references only",
            how_to_use_short="needs_owner_review:package insert not in local corpus",
            what_to_expect_soft="needs_owner_review:soft claims only from textile family",
            primary_image_url=f"confirmed:{_SNAP}/resources.tsv image-catalog-t001-primary",
        ),
    },
    "T002-00": {
        "short_name": "Шейная накладка",
        "category": "home_wellness",
        "what_it_is": "Шейная накладка Health Priority — мягкий функциональный текстиль для зоны шеи и плеч, когда воротниковая зона зажата после работы за компьютером или в дороге.",
        "who_asks_about_it": "Офисные сотрудники, водители и путешественники с хроническим напряжением в шее — по той же логике, что палантин T015, но в формате шейной накладки.",
        "common_use_cases": "шея «деревянная» к вечеру; сквозняк в машине или офисе; дополнение к палантину; ищете шейный формат Health Priority",
        "how_to_use_short": "Носите накладку на шею и плечи по инструкции в течение дня или отдыха, когда чувствуете напряжение в воротниковой зоне.",
        "what_to_expect_soft": "Её воспринимают как деликатную поддержку шеи без мазей и пластырей — в одной линейке с палантином и Health Priority текстилем.",
        "contraindications_short": "острые травмы шеи; высокая температура; индивидуальная непереносимость; кардиостимулятор — уточнить у врача",
        "do_not_claim": "Не обещать лечение остеохондроза, грыж, инсульта или замену медицинской терапии.",
        "when_to_escalate": "Острая боль в шее; онемение рук; головокружение; вопрос после травмы.",
        "primary_image_url": "https://wwc.best/media/products/T002-00/1.jpg.webp",
        "provenance_status": "needs_owner_review",
        "review_notes": "Parallel to approved T015 card; confirm exact wear pattern with owner.",
        "field_provenance": _fp(
            what_it_is=f"confirmed:{_SNAP}/products.tsv + T015 card pattern",
            who_asks_about_it=f"confirmed:{_SNAP}/product_cards.tsv T015",
            common_use_cases=f"confirmed:{_SNAP}/product_cards.tsv T015",
            how_to_use_short="needs_owner_review:package insert not in local corpus",
            what_to_expect_soft=f"confirmed:{_SNAP}/product_cards.tsv T015",
            primary_image_url=f"confirmed:{_SNAP}/resources.tsv image-catalog-t002-00-primary",
        ),
    },
    "T003": {
        "short_name": "Магнитный пояс",
        "category": "home_wellness",
        "what_it_is": "Магнитный пояс Health Priority — функциональный пояс для поясницы и живота, когда тянет спину после работы, хочется локального тепла или поддержки без мазей.",
        "who_asks_about_it": "Люди с сидячей работой, дискомфортом в пояснице и теми, кто уже использует Health Priority текстиль (стельки, палантин, наколенники).",
        "common_use_cases": "поясница ноет после сидения; хочется мягкого тепла в области поясницы; дополнение к стелькам; ищете пояс в линейке WHIEDA",
        "how_to_use_short": "Носите пояс на поясницу или живот по инструкции и подбору размера. Время ношения — по комфорту.",
        "what_to_expect_soft": "Его ценят как простой бытовой аксессуар поддержки спины — без обещаний «вылечить» диагноз.",
        "contraindications_short": "беременность; кардиостимулятор; острые воспаления; металлические импланты в зоне — уточнить у врача",
        "do_not_claim": "Не обещать лечение почек, грыж, бесплодия, диабета или замену медицинского лечения.",
        "when_to_escalate": "Беременность; кардиостимулятор; острая боль; вопрос лечения диагноза.",
        "primary_image_url": "https://wwc.best/media/products/T003/1.jpg.webp",
        "provenance_status": "needs_owner_review",
        "review_notes": "Alias «пояс» exists; partner price missing in products.tsv.",
        "extra_source_refs": [f"{_SNAP}/products.tsv partner_price_byn=-"],
        "field_provenance": _fp(
            what_it_is=f"confirmed:{_SNAP}/products.tsv + aliases.tsv",
            who_asks_about_it="needs_owner_review:thin local copy",
            common_use_cases=f"confirmed:{_SNAP}/aliases.tsv",
            how_to_use_short="needs_owner_review:package insert not in local corpus",
            what_to_expect_soft="needs_owner_review:textile family soft claim",
            primary_image_url=f"confirmed:{_SNAP}/resources.tsv image-catalog-t003-primary",
        ),
    },
    "T023": {
        "short_name": "Носки Health Priority",
        "category": "home_wellness",
        "what_it_is": "Носки Health Priority — функциональный текстиль для стоп той же линейки, что стельки и палантин. Формат на каждый день, без обещания лечения.",
        "who_asks_about_it": "Люди, которые уже используют стельки, палантин или другие Health Priority продукты и хотят усилить «текстильный» слой ухода за стопами.",
        "common_use_cases": "стопы устают к вечеру; ищете носки линейки Health Priority; дополнение к стелькам D013; холодные или «тяжёлые» ноги",
        "how_to_use_short": "Носите как обычные носки в повседневной обуви в течение дня. Меняйте и стирайте по стандартному уходу за текстилем.",
        "what_to_expect_soft": "Их воспринимают как простой ежедневный аксессуар комфорта для стоп в экосистеме Health Priority.",
        "contraindications_short": "открытые раны на стопах; мокнущие раны; индивидуальная непереносимость материалов",
        "do_not_claim": "Не обещать лечение варикоза, диабета, грибка или замену медицинского лечения.",
        "when_to_escalate": "Гнойное воспаление; диабетическая стопа; вопрос лечения диагноза.",
        "primary_image_url": "https://wwc.best/media/products/T023/1.jpg.webp",
        "provenance_status": "needs_owner_review",
        "review_notes": "Graphene/anion family reference from RAG; confirm exact material claim with owner.",
        "field_provenance": _fp(
            what_it_is=f"confirmed:{_SNAP}/products.tsv + {_OBS}/Очки, анионы.../Выжимка RAW.md",
            who_asks_about_it=f"confirmed:{_SNAP}/product_cards.tsv D013 audience overlap",
            common_use_cases=f"confirmed:{_SNAP}/product_cards.tsv D013 pattern",
            how_to_use_short="confirmed:standard textile wear pattern",
            what_to_expect_soft=f"confirmed:{_OBS}/Очки, анионы.../Выжимка RAW.md",
            primary_image_url=f"confirmed:{_SNAP}/resources.tsv image-website-t023-001",
        ),
    },
}
