-- Support tunnel: a subscriber talks to a service administrator only through the
-- bot; neither side sees the other's Telegram contact. Additive, idempotent.
--
-- The administrator for a channel is NOT stored here: staging and production
-- share this database, and staging must route to the owner while production
-- routes to the real administrator. The id comes from
-- PLATFORM_SUPPORT_ADMIN_TELEGRAM_ID in each environment's .env.
begin;

create table if not exists support_tickets (
  ticket_id uuid primary key default gen_random_uuid(),
  -- Human number for both sides: "#S-1042". One sequence across tenants is fine.
  ticket_no bigint generated by default as identity,
  tenant_id text not null references tenants (tenant_id),
  channel_code text not null,
  offer_code text,
  offer_title text,
  user_telegram_user_id bigint not null,
  user_chat_id bigint not null,
  user_display text not null,
  admin_telegram_user_id bigint not null,
  status text not null default 'open' check (status in ('open', 'closed')),
  created_at timestamptz not null default now(),
  last_message_at timestamptz not null default now(),
  closed_at timestamptz,
  closed_by text check (closed_by in ('admin', 'user', 'system'))
);

-- One open ticket per person and channel; a second order joins the same tunnel.
create unique index if not exists uq_support_tickets_open_user_channel
  on support_tickets (tenant_id, channel_code, user_telegram_user_id)
  where status = 'open';
create index if not exists idx_support_tickets_admin_open
  on support_tickets (tenant_id, admin_telegram_user_id, status, last_message_at desc);

create table if not exists support_messages (
  message_id uuid primary key default gen_random_uuid(),
  tenant_id text not null references tenants (tenant_id),
  ticket_id uuid not null references support_tickets (ticket_id) on delete cascade,
  direction text not null check (direction in ('user_to_admin', 'admin_to_user', 'system')),
  text text,
  telegram_file_id text,
  -- Where the message came from and where the bot delivered it. The delivered
  -- id in the admin chat is what a Reply points back to.
  source_chat_id bigint,
  source_message_id bigint,
  delivered_chat_id bigint,
  delivered_message_id bigint,
  created_at timestamptz not null default now()
);

create index if not exists idx_support_messages_ticket
  on support_messages (tenant_id, ticket_id, created_at);
create unique index if not exists uq_support_messages_delivered
  on support_messages (tenant_id, delivered_chat_id, delivered_message_id)
  where delivered_message_id is not null;
-- Telegram may retry an update; the same source message must not relay twice.
create unique index if not exists uq_support_messages_source
  on support_messages (tenant_id, source_chat_id, source_message_id)
  where source_message_id is not null;

alter table support_tickets enable row level security;
drop policy if exists support_tickets_tenant_isolation on support_tickets;
create policy support_tickets_tenant_isolation on support_tickets
  using (tenant_id = platform_current_tenant_id())
  with check (tenant_id = platform_current_tenant_id());

alter table support_messages enable row level security;
drop policy if exists support_messages_tenant_isolation on support_messages;
create policy support_messages_tenant_isolation on support_messages
  using (tenant_id = platform_current_tenant_id())
  with check (tenant_id = platform_current_tenant_id());

commit;
