"""Generate WHIEDA data-to-feature map markdown."""

from __future__ import annotations

from pathlib import Path

from inventory.constants import DEEP_CORPUS, OBSIDIAN_RAG, RAG_ROOT, SQL_CORPUS
from inventory.distillate_layers import DISTILLATE_LAYERS
from inventory.manifest import RAW_TESTIMONIALS_PATH, build_manifest_rows
from inventory.readers import count_text_lines, read_tsv_info


def _layer_section(
    title: str,
    what_exists: str,
    user_sees: str,
    why_not: str,
    min_action: str,
    approver: str,
) -> list[str]:
    return [
        f"### {title}",
        "",
        f"- **Что уже есть:** {what_exists}",
        f"- **Что может увидеть пользователь сейчас:** {user_sees}",
        f"- **Почему ещё не видит:** {why_not}",
        f"- **Минимальное действие:** {min_action}",
        f"- **Кто подтверждает:** {approver}",
        "",
    ]


def _count_tsv(name: str) -> int:
    path = SQL_CORPUS / name
    if not path.is_file():
        return -1
    return read_tsv_info(path).data_rows


def render_testimonials_registry() -> list[str]:
    lines = [
        "## Testimonials & video registry",
        "",
        "Rule: **не превращать отзыв в медицинское доказательство.**",
        "",
        "| Source | Approx volume | Author/date/link | Consent | Med/safety risk | Product link |",
        "|---|---:|---|---|---|---|",
    ]

    if RAW_TESTIMONIALS_PATH.is_file():
        raw_lines = count_text_lines(RAW_TESTIMONIALS_PATH)
        lines.append(
            f"| RAW `WHIEDA 🗣️ Отзывы.txt` | ~{raw_lines} lines | partial in export | unknown | high | partial |"
        )

    raw_dir = RAG_ROOT / "RAW диалоги с врачами"
    if raw_dir.is_dir():
        exports = list(raw_dir.glob("Copy of _Messages*.txt"))
        lines.append(
            f"| RAW Telegram `Copy of _Messages*.txt` | {len(exports)} files | per-message metadata | unknown | medium | via distillate |"
        )

    t_rows = _count_tsv("07_TESTIMONIALS.tsv")
    if t_rows >= 0:
        lines.append(
            f"| Distillate `07_TESTIMONIALS.tsv` | {t_rows} rows | columns: автор, дата, ссылка | `можно_в_маркетинг` flag | med_критичность | товар column |"
        )

    u_rows = _count_tsv("06_USAGE_PATTERNS.tsv")
    if u_rows >= 0:
        lines.append(
            f"| Distillate `06_USAGE_PATTERNS.tsv` | {u_rows} rows | source_id/locator | needs manual | `нужна_мед_проверка` | товар |"
        )

    s_rows = _count_tsv("15_SAFETY_SIGNALS.tsv")
    if s_rows >= 0:
        lines.append(
            f"| Distillate `15_SAFETY_SIGNALS.tsv` | {s_rows} rows | raw_quote | blocked | high | товар |"
        )

    if OBSIDIAN_RAG.is_dir():
        obs_reviews = OBSIDIAN_RAG / "chat-analysis" / "03_блок3_отзывы_кейсы.md"
        if obs_reviews.is_file():
            lines.append(
                f"| Obsidian chat-analysis отзывы | {count_text_lines(obs_reviews)} lines | curated notes | owner | medium | manual |"
            )
        photo_cat = OBSIDIAN_RAG / "photo catalog"
        if photo_cat.is_dir():
            photos = sum(1 for _ in photo_cat.rglob("*") if _.is_file())
            lines.append(
                f"| Obsidian photo catalog | {photos} files | filenames | unknown | low | product photos |"
            )

    lines.append("")
    return lines


def render_data_to_feature_map(manifest_rows: int) -> str:
    lines = [
        "# WHIEDA Data → Feature Map",
        "",
        "Date: 2026-08-09",
        "Generated by read-only inventory scan. No live/Sheets/Dify changes.",
        "",
        f"Manifest logical sources scanned: **{manifest_rows}**",
        "",
        "## Priority assets (owner view)",
        "",
    ]

    highlights = [
        ("RAW testimonials", RAW_TESTIMONIALS_PATH, "~7996 non-empty lines (total-line count differs)"),
        ("Distillate testimonials", "07_TESTIMONIALS.tsv", "73 rows selected"),
        ("Usage patterns", "06_USAGE_PATTERNS.tsv", "156 rows"),
        ("Problem → Solution", "08_PROBLEM_SOLUTION_CANDIDATES.tsv", "59 candidates"),
        ("Bundles", "09_BUNDLE_CANDIDATES.tsv", "25 bundles"),
        ("Medical review queue", "10_MEDICAL_REVIEW_QUEUE.tsv", "109 rows"),
        ("Safety signals", "15_SAFETY_SIGNALS.tsv", "56 signals"),
        ("Deep corpus", str(DEEP_CORPUS), "14 markdown documents"),
        ("Resource links", "12_RESOURCE_LINKS.tsv", "37 links"),
        ("Objections", "05_OBJECTIONS.tsv", "37 rows"),
        ("Parity smoke", "qa/parity/core_local_parity_cases_v2.jsonl", "85 cases"),
        ("Distillate smoke", "13_SMOKE_CASES.tsv", "83 cases"),
    ]
    lines.append("| Asset | Location | Count |")
    lines.append("|---|---|---:|")
    for title, loc, count in highlights:
        if isinstance(loc, Path):
            loc_str = str(loc.relative_to(RAG_ROOT.parent.parent)) if loc.is_absolute() else str(loc)
        else:
            loc_str = f"RAG/.../2_SQL_корпус_из_RAW/{loc}" if loc.endswith(".tsv") else loc
        lines.append(f"| {title} | `{loc_str}` | {count} |")
    lines.extend(["", "## Distillate layers", ""])

    for layer in DISTILLATE_LAYERS:
        rows = _count_tsv(layer.filename)
        count_text = str(rows) if rows >= 0 else "missing"
        lines.extend(
            _layer_section(
                f"{layer.title} (`{layer.filename}`, {count_text} rows)",
                f"{layer.key_fields}. Purpose: {layer.user_purpose}",
                "no — distillate not auto-published",
                f"Target {layer.target_destination}; can_publish={layer.can_publish_now}; flag={layer.review_flag}",
                f"Import approved rows only into {layer.target_destination}; respect {layer.review_flag}",
                "owner / doctor / business-leader per layer",
            )
        )

    lines.extend(render_testimonials_registry())

    lines.extend(
        [
            "## Runtime vs distillate gap",
            "",
            "| User function | Runtime today (prod) | Distillate ready | Gap |",
            "|---|---|---|---|",
            "| Card/price/media | Telegram: Core live; site advisor: shadow; Sheets sync | Questions, aliases, resources | Importer frozen; user smoke pending |",
            "| FAQ/objections | Core code + partial Sheets | 35 FAQ + 37 objections | Business review queue |",
            "| Testimonials | Not in advisor | 73 distilled | BLOCKED — consent |",
            "| Bundles | Starter basket only | 25 candidates | Doctor/leader review |",
            "| Deep answers | OFF (`CORE_ROUTE_DEEP=off`) | 14 deep docs in Dify | Route switch + safety |",
            "| Gaps operator view | knowledge_gap mode in Core | 34 gap rows | No operator UI |",
            "",
            "## Buckets",
            "",
            "### Ready to connect (after review slice)",
            "",
            "- `02_ALIASES.tsv` owner-approved → `advisor_structured_aliases`",
            "- `03_SQL_FAQ_CANDIDATES.tsv` business-approved → `advisor_structured_business_faq`",
            "- `05_OBJECTIONS.tsv` → `advisor_structured_business_objections`",
            "- `12_RESOURCE_LINKS.tsv` URL-validated → `advisor_structured_resources`",
            "- `04_CLARIFICATION_RULES.tsv` → clarification prompts (merge with Core synthetic)",
            "",
            "### Needs review (do not auto-connect)",
            "",
            "- `07_TESTIMONIALS.tsv`, `06_USAGE_PATTERNS.tsv` — marketing only, not medical proof",
            "- `10_MEDICAL_REVIEW_QUEUE.tsv` — doctor",
            "- `15_SAFETY_SIGNALS.tsv` — doctor + safety policy",
            "- `09_BUNDLE_CANDIDATES.tsv`, `17_CONTRADICTIONS.tsv`, `16_COMMUNITY_BELIEFS.tsv`",
            "- `18_DIALOGUE_FLOWS.tsv` — provenance_verified required",
            "- `CORPUS_REPAIR_QUARANTINE.tsv` — audit only",
            "",
            "### Not found / missing",
            "",
            "- Internet/web search advisor capability",
            "- Live operator gap dashboard",
            "- Real-user Telegram Core smoke after cutover 2026-08-09",
            "- Automated distillate → Postgres importer in production path (frozen by policy)",
            "",
        ]
    )
    return "\n".join(lines)


def write_data_to_feature_map(path: Path, manifest_row_count: int) -> None:
    path.write_text(render_data_to_feature_map(manifest_row_count), encoding="utf-8")
