"""Distillate TSV layer metadata for inventory maps."""

from __future__ import annotations

from dataclasses import dataclass


@dataclass(frozen=True)
class DistillateLayer:
    filename: str
    asset_id: str
    title: str
    layer: str
    key_fields: str
    user_purpose: str
    target_destination: str
    can_publish_now: str
    depends_on: str
    review_flag: str  # ok | review_required | blocked_raw


DISTILLATE_LAYERS: tuple[DistillateLayer, ...] = (
    DistillateLayer(
        "00_SOURCE_REGISTER.tsv",
        "DIST-00-SOURCE-REGISTER",
        "Source register",
        "distillate",
        "source_id, имя_файла, тип_источника, статус_обработки",
        "Карта сырья: откуда взяты строки дистиллята",
        "operator / owner",
        "no",
        "RAW exports",
        "ok",
    ),
    DistillateLayer(
        "01_QUESTIONS.tsv",
        "DIST-01-QUESTIONS",
        "Question corpus",
        "distillate",
        "question_id, исходный_вопрос, намерение, publication_status",
        "Понимание типовых вопросов пользователей",
        "SQL canonical / smoke / RAG routing",
        "partial — после business review строк с флагом",
        "RAW dialogues",
        "review_required",
    ),
    DistillateLayer(
        "02_ALIASES.tsv",
        "DIST-02-ALIASES",
        "Product aliases",
        "distillate",
        "алиас, товар_или_тема, уверенность",
        "Разговорные имена товаров → canonical SKU",
        "SQL advisor_structured_aliases",
        "partial — только owner-approved",
        "01_QUESTIONS, product master",
        "review_required",
    ),
    DistillateLayer(
        "03_SQL_FAQ_CANDIDATES.tsv",
        "DIST-03-FAQ",
        "Business FAQ candidates",
        "distillate",
        "faq_id, канонический_вопрос, короткий_ответ",
        "PV, повторка, бинар, старт — без выдумок",
        "SQL advisor_structured_business_faq",
        "no — business review",
        "01_QUESTIONS",
        "review_required",
    ),
    DistillateLayer(
        "04_CLARIFICATION_RULES.tsv",
        "DIST-04-CLARIFICATION",
        "Clarification rules",
        "distillate",
        "исходная_неоднозначная_фраза, уточняющий_вопрос",
        "Уточнения вместо fallback (паста, цвет, пояс)",
        "SQL advisor_structured_clarification_prompts",
        "partial — Core уже имеет synthetic prompts",
        "02_ALIASES",
        "review_required",
    ),
    DistillateLayer(
        "05_OBJECTIONS.tsv",
        "DIST-05-OBJECTIONS",
        "Objections",
        "distillate",
        "возражение, рекомендуемая_структура_ответа",
        "MLM, цена, скепсис — структурированный ответ",
        "SQL advisor_structured_business_objections + coach",
        "no — business review",
        "01_QUESTIONS",
        "review_required",
    ),
    DistillateLayer(
        "06_USAGE_PATTERNS.tsv",
        "DIST-06-USAGE",
        "Usage patterns",
        "distillate",
        "товар, ситуация, как_использовали, уровень_риска",
        "Контекст применения без медицинских обещаний",
        "review → card detail / coach (не auto)",
        "no — medical review on flagged rows",
        "RAW testimonials",
        "review_required",
    ),
    DistillateLayer(
        "07_TESTIMONIALS.tsv",
        "DIST-07-TESTIMONIALS",
        "Testimonials",
        "testimonials",
        "testimonial_id, товар, результат_словами_автора, можно_в_маркетинг",
        "Социальное доказательство — не медицинский факт",
        "marketing / owner-approved snippets only",
        "no — consent + manual review",
        "RAW отзывы",
        "blocked_raw",
    ),
    DistillateLayer(
        "08_PROBLEM_SOLUTION_CANDIDATES.tsv",
        "DIST-08-PROBLEM-SOLUTION",
        "Problem → Solution",
        "distillate",
        "проблема, товары, число_независимых_упоминаний",
        "Подбор направления без диагноза",
        "SQL routing / coach / bundles",
        "no — medical review",
        "06_USAGE_PATTERNS, 07_TESTIMONIALS",
        "review_required",
    ),
    DistillateLayer(
        "09_BUNDLE_CANDIDATES.tsv",
        "DIST-09-BUNDLES",
        "Bundle candidates",
        "bundles",
        "название_ситуации, основной_товар, доп_товары, нужен_врач",
        "Связки товаров под ситуацию",
        "starter basket / cart suggestions",
        "no — doctor + leader review",
        "08_PROBLEM_SOLUTION",
        "blocked_raw",
    ),
    DistillateLayer(
        "10_MEDICAL_REVIEW_QUEUE.tsv",
        "DIST-10-MEDICAL",
        "Medical review queue",
        "medical",
        "исходная_цитата, тип_риска, severity",
        "Очередь врачу — нейтральные формулировки",
        "doctor review only",
        "no",
        "RAW medical mentions",
        "blocked_raw",
    ),
    DistillateLayer(
        "11_MARKETING_LANGUAGE.tsv",
        "DIST-11-MARKETING",
        "Marketing language",
        "marketing",
        "исходная_фраза, риск_или_ограничение",
        "Разрешённые маркетинговые формулировки",
        "business review → cards / FAQ",
        "no",
        "07_TESTIMONIALS",
        "review_required",
    ),
    DistillateLayer(
        "12_RESOURCE_LINKS.tsv",
        "DIST-12-RESOURCES",
        "Resource links",
        "media",
        "товар, тип_материала, url",
        "Фото, видео, PDF, сертификаты",
        "SQL advisor_structured_resources",
        "partial — URL validation required",
        "Google Sheets Resource_Links / Obsidian",
        "review_required",
    ),
    DistillateLayer(
        "13_SMOKE_CASES.tsv",
        "DIST-13-SMOKE",
        "Distillate smoke cases",
        "qa",
        "case_id, входной_запрос, ожидаемый_intent",
        "Регрессия качества ответов",
        "qa parity / acceptance (не runtime)",
        "yes as QA only",
        "01_QUESTIONS",
        "ok",
    ),
    DistillateLayer(
        "14_KNOWLEDGE_GAPS.tsv",
        "DIST-14-GAPS",
        "Knowledge gaps",
        "distillate",
        "вопрос_или_тема, что_запросить, у_кого_запросить",
        "Честный gap + следующий шаг для оператора",
        "SQL gap prompts / operator queue",
        "partial — operator workflow not live",
        "01_QUESTIONS",
        "review_required",
    ),
    DistillateLayer(
        "15_SAFETY_SIGNALS.tsv",
        "DIST-15-SAFETY",
        "Safety signals",
        "safety",
        "товар, событие, тяжесть, причинность",
        "Сигналы безопасности — не публиковать как факты",
        "doctor review → safety clarifications",
        "no",
        "RAW dialogues",
        "blocked_raw",
    ),
    DistillateLayer(
        "16_COMMUNITY_BELIEFS.tsv",
        "DIST-16-BELIEFS",
        "Community beliefs",
        "distillate",
        "точная_формулировка, официальный_статус, потенциальный_риск",
        "Распространённые мифы/убеждения",
        "business + medical review",
        "no",
        "RAW",
        "blocked_raw",
    ),
    DistillateLayer(
        "17_CONTRADICTIONS.tsv",
        "DIST-17-CONTRADICTIONS",
        "Contradictions",
        "distillate",
        "сторона_А, сторона_Б, тип_противоречия",
        "Противоречия в RAW — не auto-merge",
        "owner / doctor resolution",
        "no",
        "multiple layers",
        "blocked_raw",
    ),
    DistillateLayer(
        "18_DIALOGUE_FLOWS.tsv",
        "DIST-18-FLOWS",
        "Dialogue flows",
        "distillate",
        "flow_type, follow_up, нужный_structured_route",
        "Multi-turn сценарии",
        "engine routing / coach",
        "no — provenance_verified required",
        "01_QUESTIONS, RAW",
        "blocked_raw",
    ),
    DistillateLayer(
        "CORPUS_REPAIR_QUARANTINE.tsv",
        "DIST-QUARANTINE",
        "Corpus quarantine log",
        "distillate",
        "file, reason, resolution_status",
        "Строки, выведенные из публикации при repair",
        "operator audit only",
        "no",
        "all distillate passes",
        "blocked_raw",
    ),
    DistillateLayer(
        "CORPUS_VALIDATION_ERRORS.tsv",
        "DIST-VALIDATION-ERRORS",
        "Validation errors log",
        "qa",
        "file, row, error_type",
        "Ошибки валидации корпуса",
        "operator / QA",
        "no",
        "distillate pipeline",
        "ok",
    ),
)

DISTILLATE_BY_FILENAME = {layer.filename: layer for layer in DISTILLATE_LAYERS}
