"""Expand the existing /report command with runtime activity metrics."""
import importlib.util, json
from datetime import datetime
from pathlib import Path

BASE = Path(__file__).resolve().parent
def load():
    p=BASE/'publish_and_run_whieda_sync_2026-07-13.py'; s=importlib.util.spec_from_file_location('w',p); m=importlib.util.module_from_spec(s); s.loader.exec_module(m); return m
def main():
    h=load(); q=h.login_session(); wid='advisor-whieda-phase1'; w=q.get(f'{h.BASE_URL}/rest/workflows/{wid}',verify=False,timeout=60).json()['data']
    b=BASE.parent/'backups'; b.mkdir(parents=True,exist_ok=True); bp=b/f'advisor-whieda-before-superadmin-report-{datetime.now():%Y%m%d-%H%M%S}.json'; bp.write_text(json.dumps(w,ensure_ascii=False,indent=2),encoding='utf-8')
    nodes={n['name']:n for n in w['nodes']}
    nodes['Postgres: Owner funnel report']['parameters']['query']="WITH base AS (SELECT initial_ref_code, attributed_owner_id, status, created_at FROM website_leads WHERE tenant_id='whieda'), t AS (SELECT count(*)::int total,count(*) FILTER(WHERE created_at>=date_trunc('day',now() AT TIME ZONE 'Europe/Moscow') AT TIME ZONE 'Europe/Moscow')::int today,count(*) FILTER(WHERE created_at>=now()-interval '7 days')::int week,count(*) FILTER(WHERE status='new')::int new_total,count(*) FILTER(WHERE status='in_progress')::int in_progress_total,count(*) FILTER(WHERE status IN ('new','in_progress'))::int active_total,count(*) FILTER(WHERE status='completed')::int completed_total FROM base), r AS (SELECT coalesce(nullif(initial_ref_code,''),'без ref') ref_code,coalesce(nullif(attributed_owner_id,''),'viktor') owner_id,count(*)::int total,count(*) FILTER(WHERE status IN ('new','in_progress'))::int active,count(*) FILTER(WHERE created_at>=now()-interval '30 days')::int last_30_days FROM base GROUP BY 1,2 ORDER BY count(*) DESC,1 LIMIT 12), a AS (SELECT (SELECT count(*)::int FROM advisor_telegram_subscriptions WHERE client_id='whieda' AND last_seen_at>=now()-interval '30 days') active_users_30d,(SELECT count(*)::int FROM advisor_events WHERE event_type IN ('advisor_reply','knowledge_gap','error','escalation') AND created_at>=now()-interval '30 days') questions_30d,(SELECT count(*)::int FROM advisor_events WHERE event_type='advisor_reply' AND coalesce(sidecar->>'answer_mode','') LIKE 'direct_structured%' AND created_at>=now()-interval '30 days') sql_answers_30d,(SELECT count(*)::int FROM advisor_events WHERE event_type='advisor_reply' AND coalesce(sidecar->>'answer_mode','') LIKE 'deep_%' AND created_at>=now()-interval '30 days') rag_answers_30d,(SELECT count(*)::int FROM advisor_events WHERE event_type='advisor_reply' AND coalesce(sidecar->>'answer_mode','') LIKE '%fallback%' AND created_at>=now()-interval '30 days') fallback_30d,(SELECT count(*)::int FROM advisor_events WHERE event_type='advisor_reply' AND coalesce(sidecar->>'answer_mode','') LIKE '%clarification%' AND created_at>=now()-interval '30 days') clarifications_30d,(SELECT count(*)::int FROM advisor_review_queue WHERE client_id='whieda' AND coalesce(queue_status,status,'pending') IN ('pending','in_work')) unresolved_reviews) SELECT t.*,a.*,coalesce((SELECT jsonb_agg(r) FROM r),'[]'::jsonb) refs FROM t CROSS JOIN a;"
    nodes['Code: Format owner report']['parameters']['jsCode']="const c=$('Code: Route /leads').first().json,x=$input.first().json||{},n=v=>Number(v||0).toLocaleString('ru-RU');let r=x.refs||[];if(typeof r==='string'){try{r=JSON.parse(r)}catch{r=[]}}if(!Array.isArray(r))r=[];const refs=r.length?r.map(v=>`• <b>${v.ref_code||'без ref'}</b> — ${n(v.total)} всего · ${n(v.active)} активных`).join('\\n'):'Пока нет заявок.';return[{json:{external_chat_id:c.external_chat_id,telegram_text:`<b>Сводка WHIEDA</b>\\n\\n<b>Консультант, 30 дней</b>\\nПользователи: <b>${n(x.active_users_30d)}</b> · вопросов: <b>${n(x.questions_30d)}</b>\\nSQL: ${n(x.sql_answers_30d)} · глубокие: ${n(x.rag_answers_30d)} · уточнения: ${n(x.clarifications_30d)} · fallback: ${n(x.fallback_30d)}\\nНерешённые вопросы: <b>${n(x.unresolved_reviews)}</b>\\n\\n<b>Заявки</b>\\nСегодня: <b>${n(x.today)}</b> · за 7 дней: <b>${n(x.week)}</b> · всего: <b>${n(x.total)}</b>\\nАктивные: <b>${n(x.active_total)}</b> — новые ${n(x.new_total)}, в работе ${n(x.in_progress_total)}\\nЗавершённые: <b>${n(x.completed_total)}</b>\\n\\n<b>По ref</b>\\n${refs}`,reply_markup:{inline_keyboard:[]}}}];"
    z=q.patch(f'{h.BASE_URL}/rest/workflows/{wid}',json=w,verify=False,timeout=120); z.raise_for_status(); v=z.json().get('data',z.json()).get('versionId'); q.post(f'{h.BASE_URL}/rest/workflows/{wid}/activate',json={'versionId':v},verify=False,timeout=60).raise_for_status(); h.ssh_run(f'docker exec n8n-n8n-1 n8n publish:workflow --id={wid}'); h.ssh_run('docker restart n8n-n8n-1'); h.wait_for_n8n_ready(); print(json.dumps({'version_id':v,'backup':str(bp)},ensure_ascii=False))
if __name__=='__main__':main()
